### ISSUE TITLE
Finish at some point and nothing return

### ISSUE THREAD

**Issue by girishghoda** [reswifq/pool#3]
Hi @valeriomazzeo , I copied Pool.swift file in project & used it , but at some time when i call 
 
let objectPool = Pool(maxElementCount: 1500, factory: { () -> xxxObjectName in
            
            return xxxObjectName()
        })
let xxxObject = try objectPool.draw() 

//Below code call but sometime nothing run or return
guard self.semaphore.wait(timeout: .distantFuture) == .success else {
            throw PoolError.drawTimeOut
        }
please any idea for this issue
Thank you

**Comment by valeriomazzeo** [comment]
It looks like you are not releasing any of the objects that you are drawing.

I am happy to have a look if you can create a pull request with a failing test.

**Comment by girishghoda** [comment]
Hi @valeriomazzeo oh yeah you are right , i used draw() but not release
but can you explain what is relation between this issue & release object function
Thank you

**Comment by girishghoda** [comment]
Hi @valeriomazzeo Okey i understand the code you can append in elements array when user release the object otherwise array return empty & new object create every time.
BTW Thank you for help.

**Comment by valeriomazzeo** [comment]
The whole point of having a pool is to re-use stuff, otherwise it would just be a factory...
